name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run Lighthouse CI
        env: 
          LHCI_TOKEN_ENV: ${{ secrets.LHCI_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
